### ISSUE TITLE
RFC Extending bundle configuration

### ISSUE THREAD

**Issue by MattKetmo** [broadway/broadway#227]
I love Broadway because of its simplicity and the use of interfaces everywhere which allows me to create my own implementations. However I don't use the current bundle because it doesn't allow me to use my custom implementations. I'd like to suggest you a change in the configuration tree for `event_store` (which could also be applied for saga and read_model):

``` yaml
broadway:
    event_store:
        default:
            type: dbal
            table: events
            use_binary: false 
        other:
            type: service
            id: my_acme.event_store
```

Foreach key under `event_store` an EventStore service `broadway.event_store.<name>` is created. Type would be `dbal` or `mongodb` for built-in implementations or `service` for custom one. You could also be able to create 2 dbal event stores if you want to.

I wanted to have your opinion before submitting a PR.
Thanks.
